### ISSUE TITLE
Import the hensley_draine_2017 model

### ISSUE THREAD

**Issue by zonca** [healpy/pysm#20]
Longer term, it would be nice to import the `hensley_draine_2017` dust model, which is possibly the most complex model available in PySM. This could even require changing the architecture of PySM 3.

**Comment by zonca** [comment]
@bthorne93 are you still interested in working on this? Do you have an estimate of when you would have time to work on this?

**Comment by bthorne93** [comment]
@zonca Yes, sure. I actually have most of this implemented from when we spoke about it last. I can block off some time to work on this Friday next week, and should be doable in half a day. Would that be alright?

**Comment by zonca** [comment]
that is great, not much hurry, within 3 weeks would work great

**Comment by zonca** [comment]
@bthorne93 do you think you'll be able to work on this next week? I am trying to get all the PySM 2 models into PySM 3

**Comment by zonca** [comment]
@bthorne93 as of 5b124e8 I have implemented all PySM 2 models into PySM 3 except the 3 HD models.
Can you please complete the port before the break? if not, can you please point me to your work in progress so I can start from there?

**Comment by bthorne93** [comment]
@zonca this now exists on the branch `hd17`. I have the model implemented in a way that is equivalent to PySM v2. However, before making a pull request: it seems that `sky.get_emission` does not behave in the way I expect.

**Comment by bthorne93** [comment]
`hd17` now cooperates with the new API to assume one channel being evaluated. Will need to be refactored, as currently it holds all the individual frequencies in memory, then integrates over the bandpass.

**Comment by zonca** [comment]
Thanks! This helps me a lot!
I'll pickup from here

**Comment by bthorne93** [comment]
I just pushed what I had left on my local version, which I think is closer to the correct way of doing it. I'll leave it to you from here, then!

**Comment by zonca** [comment]
implemented in #37 and #51
