### ISSUE TITLE
Looking for beta testers

### ISSUE THREAD

**Issue by zonca** [healpy/pysm#35]
All PySM 2 models except HD2017 dust are implemented.

Looking for beta-testers, please look at the docs:
http://pysm3.readthedocs.org/

Try to install and run some models, if you find bugs, please open a dedicated issue.
If you have general feedback, please reply here. In particular I am looking for high level feedback:

* is there any feature you need that is missing?
* can the interface be simplified?
* do you have suggestions for better function/classes names?
* can the docs be improved?

**Comment by dpole** [comment]
Thanks a lot @zonca. I'll upgrade the fgbuster dependency to pysm3 and let you know if I have comments.

**Comment by zonca** [comment]
Now I also have a conda package: https://anaconda.org/conda-forge/pysm3
Still, for now better to build from source as the package is changing a lot, but for a quick test, the conda package is fine.

**Comment by yaojian95** [comment]
Thanks for your effort to update the PySM2 package @zonca ! 

So except for the improvements for engineering part, what's the main scientific differences from PySM2?

**Comment by zonca** [comment]
Nothing yet, but next will add all models from https://github.com/simonsobs/so_pysm_models with resolution up to 8192

**Comment by zonca** [comment]
@aiolasimone, just released PySM 3.2.0,
this is the first release which includes all the models, it would be nice to have more beta-testers,
install instructions at https://pysm3.readthedocs.io/en/latest/#installation
