### ISSUE TITLE
Return shape of `ModifiedBlackBody.get_emission` for array inputs

### ISSUE THREAD

**Issue by bthorne93** [healpy/pysm#36]
When executing the following code:

```python
import numpy as np
import pysm
freqs = np.linspace(10, 400, 100) * u.GHz
sky = pysm.Sky(nside=nside, preset_strings=['d1'])
emission_d1 = sky.get_emission(freqs)
print(emission_d1.shape)
```
I get an array of shape (3, npix), rather than (nfreqs, 3, npix). This is not the expected behavior according to the docstring. It looks like the code automatically defines a 'bandpass' with equal weight at each of these frequencies, and averages over them.

**Comment by zonca** [comment]
Sorry, I need to update the docstring.
I decided to simplify the API, if you want separate frequencies not integrated you need to run the method multiple times
