### ISSUE TITLE
installing PySM3 at NERSC

### ISSUE THREAD

**Issue by NicolettaK** [healpy/pysm#40]
I'm having problems at installing pysm3 at nersc.
I'm using the `pip install pysm3` command with the `--prefix` option and getting the following error:

`   ERROR: Command errored out with exit status 1:
     command: /usr/common/software/tensorflow/gpu-tensorflow/1.15.0-py37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-aftj8io3/pysm3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-aftj8io3/pysm3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-aftj8io3/pysm3/pip-egg-info
         cwd: /tmp/pip-install-aftj8io3/pysm3/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-aftj8io3/pysm3/setup.py", line 51, in <module>
        from astropy_helpers.setup_helpers import (
    ModuleNotFoundError: No module named 'astropy_helpers.setup_helpers'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by zonca** [comment]
Have you tried the conda package?

**Comment by NicolettaK** [comment]
No, I usually prefer to use pip at NERSC, but I can try with conda if you recommend so.

**Comment by zonca** [comment]
Do you want to also install mapsims?

**Comment by NicolettaK** [comment]
great! thanks!

**Comment by zonca** [comment]
give me a few days, I want to find a way to properly handle once and for all the case of running on the login node (where I cannot import `mpi4py`).

**Comment by zonca** [comment]
@NicolettaK for now do:

```
module load python/3.7-anaconda-2019.10
conda create -c conda-forge -n pysm pysm3 python=3.7 ipython
conda activate pysm
module unload python
```

I found the last step needed otherwise it always loads the base environment.

Then quick test:

```
python -c "import pysm;sky=pysm.Sky(nside=64, preset_strings=['d1']);print(sky.get_emission(12*pysm.units.GHz)[:5])"
[[ 0.05146998  0.05273027  0.06248602 ...  0.04509924  0.06567437
   0.0677657 ]
 [ 0.00080898 -0.00050239  0.00052695 ...  0.00210943 -0.00166372
   0.00063091]
 [-0.00293329  0.00108048 -0.00223178 ... -0.00236847  0.00317197
   0.00120832]] uK_RJ
```

**Comment by NicolettaK** [comment]
It worked. Thanks!

**Comment by dpole** [comment]
I've got the same problem when installing pysm3 in a clean conda environment on my laptop. `pip install pysm3` fails with Nico's error message.

Installing the pysm3 through conda works, but I'd like to add pysm3 as a dependency to another package that I is currently pip-installable.

**Comment by zonca** [comment]
Have you tried installing astropy_helpers?

**Comment by dpole** [comment]
Thanks. Yes, if I installed the modules by hand it worked. However, I found that the problem was that `pip` was picking the system install instead of the one on the conda environment. Probably I initialized the environment with `conda create -n myenv` instead of `conda create -n myenv python=3.7`. In the latter case everything works. I hope this saves others' time...
