### ISSUE TITLE
Unable to reproduce Haslam map.

### ISSUE THREAD

**Issue by martinjameswhite** [healpy/pysm#44]
I think I must be doing something wrong with the synchrotron maps since I am unable to reproduce the Haslam 408MHz map; see attached notebook.

[CheckHaslam_pysm3.ipynb.gz](https://github.com/healpy/pysm/files/4327433/CheckHaslam_pysm3.ipynb.gz)

**Comment by zonca** [comment]
thanks @martinjameswhite for reporting this.

I confirm there is a bug in the unit handling, we usually only use GHz so never noticed,
I'll work on a fix and close the issue when this is solved.

In the meantime use GHz: https://gist.github.com/zonca/12e92bc3bdf0750654229facd8443319

**Comment by martinjameswhite** [comment]
Thanks!  I'll switch to GHz for now.
