### ISSUE TITLE
Making Gaussian realisaions of foregrounds ?

### ISSUE THREAD

**Issue by YutoMinami** [healpy/pysm#48]
For the validation, I'd like to make some different realisations of foregrounds assuming Gaussian variance. Are there any way to implement this in PySM?
I can realise using healpy for each output frequency map. However, foreground maps should be correlated among frequencies. I think I have to create different realisations before the colour corrections.

**Comment by zonca** [comment]
the components included in PySM are deterministic.
Maybe you can check this:
https://so-pysm-models.readthedocs.io/en/latest/models.html#gaussiansynchrotron

**Comment by YutoMinami** [comment]
Thank you. The page looks very helpful for me.
As a tentative treatment, I made different realisations of a pivot frequency map following Gaussian fluctuations, and extrapolate them to each frequency as d1 or s1 models in PySM do.
