### ISSUE TITLE
ImportError for importlib_resources in python 3.6

### ISSUE THREAD

**Issue by dpole** [healpy/pysm#58]
Apparently `importlib_resources` doesn't get installed in python 3.6 but seems to be required.
Is it something to be fixed in the install process or is it a problem on my side?

**Comment by zonca** [comment]
Are you installing with pip from PyPI?

**Comment by dpole** [comment]
No. I install it as a dependency of another library, cloning the master branch of the github repo:
`pysm3 @ git+http://github.com/healpy/pysm.git@master#egg=pysm` in the `install_requires` of my `setup.py`

**Comment by zonca** [comment]
I would recommend to use published releases on PyPI. Master could be broken from time to time.
Can you check if this happens also installing from PyPI?

**Comment by dpole** [comment]
Yes, it worked. I think I used to need the dev version but it doesn't seem to be the case anymore. thanks.

**Comment by zonca** [comment]
great news!

**Comment by dpole** [comment]
I realized that I didn't remove my workaround (`importlib_resources` in addition to `pysm3` in my `install_requires`). If I remove it, I still get an error from `pysm.sky` because `import_resources` doesn't get installed with `pysm3`. Any idea? Not urgent anyway

**Comment by zonca** [comment]
thanks @dpole, it was actually missing from the dependencies, I just released 3.2.2, can you please test it?

**Comment by dpole** [comment]
Yes, it now installs and runs smoothly. Thanks for the quick action
