### ISSUE TITLE
macOS Catalina Compatibility Issues?

### ISSUE THREAD

**Issue by brandonshensley** [healpy/pysm#65]
I recently updated my Mac OS to Catalina, and the first thing post-upgrade was getting my Python packages back up and running. Unfortunately, I was unable to get pysm3 to install via conda following the docs, though the pip install worked without issue. Perhaps that should have been a warning sign.

When I try to run the simple code:

```
import pysm3
import astropy.units as u

nside = 64
sky = pysm3.Sky(nside = nside, preset_strings = ['d0'])
test_map = sky.get_emission(250.*u.GHz)
smooth_map = pysm3.apply_smoothing_and_coord_transform(test_map, fwhm=5./60.*u.deg)
```

I get an ominous OMP error:

> OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
> Abort trap: 6

I will try the suggested workaround on my machine, but it's not an ideal fix. Any insights or suggestions would be greatly appreciated.

**Comment by zonca** [comment]
it must be `libsharp`, can you try uninstalling it?

if you are not using `libsharp`, then it must be `healpy`, in that case can you run something in `healpy` and check it works?

**Comment by brandonshensley** [comment]
Yes indeed, I get the same error when running the following:

```
import healpy as hp
import numpy as np

nside = 64
test_map = np.random.rand(hp.nside2npix(nside))
smoothed_map = hp.smoothing(test_map,fwhm=0.2)
```

**Comment by zonca** [comment]
There is a specific issue with Catalina mentioned here:
https://healpy.readthedocs.io/en/latest/install.html

Have you tried that?

**Comment by brandonshensley** [comment]
Thanks @zonca! I removed my pip installation and installed both healpy and pysm3 through conda using the instructions at the page you linked. This seems to have taken care of the problem.
